# Generated by Django 5.0 on 2023-12-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_audiencia', models.DateTimeField()),
                ('etc', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(choices=[('Brendon', 'Brendon'), ('Fulano', 'Fulano')], max_length=50)),
            ],
        ),
    ]
