# Generated by Django 5.0 on 2023-12-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='etc',
        ),
    ]
