# Generated by Django 5.0 on 2023-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendador', '0002_remove_agenda_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='classe',
            field=models.CharField(choices=[('Trabalhista', 'Trabalhista'), ('Penal', 'Penal'), ('Civil', 'Civil')], default='Penal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='responsavel',
            field=models.CharField(choices=[('Brendon', 'Brendon'), ('Raphaela', 'Raphaela')], max_length=50),
        ),
    ]
