# Generated by Django 5.0 on 2023-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agendador', '0003_agenda_classe_alter_agenda_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dt_audiencia',
            field=models.DateField(),
        ),
    ]
